### ISSUE TITLE
A little confusion about the initial PSF.

### ISSUE THREAD

**Issue by henryhudazhi** [EliasNehme/DeepSTORM3D#1]
Excuse me,
I read your papers recently, and they gave me some inspirations about my study. I'm studying on hyperspectral imaging, it's quite similar to 3d imaging about PSFs. We all both want to use PSFs to distinguish the 3rd dimension. I'm interested in the optimal PSF by FISHER information, but my math is poor, and the articles (Optimal Point Spread Function Design for 3D Imaging, Precise Three-Dimensional Scan-Free Multiple-Particle Tracking over Large Axial Ranges with Tetrapod Point Spread Functions) say less about the derivation of the method. 
Could you suggest or recommend some papers or websites to read?
Thanks.

**Comment by EliasNehme** [comment]
Hi Henry,
I would say just take a look at a textbook that covers statistical estimators. Maybe "Fundamentals of Statistical Signal Processing" by Kay, or "Mathematical Statistics: Basic Ideas And Selected Topics" by Bickel.

**Comment by henryhudazhi** [comment]
Thank you for your suggestions, i'll read the books these days.
