### ISSUE TITLE
Bug in postprocessing

### ISSUE THREAD

**Issue by ASpeiser** [EliasNehme/DeepSTORM3D#2]
I think there is a bug in your postprocessing file:
https://github.com/EliasNehme/DeepSTORM3D/blob/b7b84479162874165550b011d1ee18813138ee1b/DeepSTORM3D/postprocess_utils.py#L97

The subpixel shifts are all set to the x value instead of x,y,z.

**Comment by EliasNehme** [comment]
Thanks!
Fixed it to: ` xloc, yloc, zloc = tensor_to_np(xloc), tensor_to_np(yloc), tensor_to_np(zloc) `
