### ISSUE TITLE
RuntimeError: CUDA error: invalid device function

### ISSUE THREAD

**Issue by zhtlai** [EliasNehme/DeepSTORM3D#4]
Execuse me? Thank you for your good work. However, I'm not able to reimplement you code as an issue, i.e. RuntimeError: CUDA error: invalid device function.
I'm running your code on an Ubuntu 22.04 machine with a RTX 3080Ti graphics card. I have set up the environment using your configuration file by running 'conda env create -f environment_linux.yml'. However, when running "demo1.py", I encountered the error 'RuntimeError: CUDA error: invalid device function'.  I have made many attempts and changes. Could you help me solve this problem? Thank you very much!

**Comment by EliasNehme** [comment]
Sorry for the extremely late reply!
I'm not too sure what is the exact problem, but the environment files are now updated to the latest torch version. Installation should be smooth now.
