### ISSUE TITLE
update environment code for DeepStorm3D?

### ISSUE THREAD

**Issue by hoadleysilas** [EliasNehme/DeepSTORM3D#5]
We would like to implement DeepSTORM3D because of its unique ability to optimize the DOE(mask) in 3D microscopy.  Python has changed substantially since the original commitment to GitHub, so the env files on GitHub are no longer useful. Please update Deep:STORM3D to use current versions of Python, Torch, etc   I am writing in May 2023.
Thank you
hoadleysilas

**Comment by EliasNehme** [comment]
Sorry for the extremely late reply!
The environment files are now updated to the latest torch version. Installation should be smooth now.
