### ISSUE TITLE
Conda environment issue: ResolvePackageNotFound

### ISSUE THREAD

**Issue by marylouDHO** [EliasNehme/DeepSTORM3D#6]
Hello, thank you so much for your very detailed instructions for getting the code up and running. I am hoping to test it and run the demo, however I am having trouble getting the environment setup. When running conda env create -f environment_windows.yml I get the following: 

Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - torchvision=0.4.2

I am running anaconda v23.3.1. Since this is a newer version of anaconda, I tried restoring free channel searching, based on [this ](https://stackoverflow.com/questions/58219956/how-to-fix-resolvepackagenotfound-error-when-creating-conda-environment) suggestion. However, I still got the same error. Any advice on how to get this up and running? Do I need an older version of something? Thank you for your help.

**Comment by EliasNehme** [comment]
Sorry for the extremely late reply!
The environment files are now updated to the latest torch version. Installation should be smooth now.
