### ISSUE TITLE
No improvement in mean loss for 7 epochs (demo1)

### ISSUE THREAD

**Issue by yueyue0112** [EliasNehme/DeepSTORM3D#7]
Hi, thank you for publishing the program. I want to compare my model with DeepSTORM3D and have something wrong when running the program.
Error information:
`out_np = np.random.poisson(input_numpy[i, :, :, :], size=None)
  File "mtrand.pyx", line 3652, in numpy.random.mtrand.RandomState.poisson
  File "_common.pyx", line 883, in numpy.random._common.disc
  File "_common.pyx", line 680, in numpy.random._common.discrete_broadcast_d
  File "_common.pyx", line 413, in numpy.random._common.check_array_constraint
ValueError: lam < 0 or lam contains NaNs`
For my cuda version (12.2) is not comparable with python 3.7, I just upgraded fft function. 
Original version: `fft_res = batch_fftshift2d(torch.fft(batch_ifftshift2d(phase4D), 2, True))`
My version: `fft_res = batch_fftshift2d(torch.fft.fft2(batch_ifftshift2d(phase4D), dim=(-1, -2), norm='forward'))`

I wonder if the modification leads to the error above, but I can't figure it out for my poor knowledge on physics about microscopy.
Thanks.

**Comment by yueyue0112** [comment]
I rebuild my environment to be the same as DeepSTORM3D and there is no bug now. But I can't get good performance while running the program of demo1. It said there is no improvement for 7 epochs and break training. 
I just used the original programm and parameters. Could someone have this kind of problems or have suitable parameters or programs?

**Comment by yueyue0112** [comment]
@EliasNehme

**Comment by EliasNehme** [comment]
Hi,
That's perfectly normal - the training stops after 7 epochs without improvement on the validation data. Ther resulting model should achieve the desired performance on the test data.

**Comment by EliasNehme** [comment]
Hi,
That's perfectly normal - the training stops after 7 epochs without improvement on the validation data. Ther resulting model should achieve the desired performance on the test data.
